### ISSUE TITLE
Unable to import in python 3.6

### ISSUE THREAD

**Issue by cmaclell** [Ofekmeister/depq#7]
I'm having issues importing the pip installed package in python 3.6. In particular I get the following:

Python 3.6.1 (default, Apr  4 2017, 09:40:21)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from depq import DEPQ
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/depq/__init__.py", line 1, in <module>
    from depq import DEPQ  # pragma: no cover
ImportError: cannot import name 'DEPQ'

Although the package says on pip it supports python3, this doesn't seem to be the case.

**Comment by ofek** [comment]
Fixed, thank you.
